buildVariable: true
familyName: Noto Sans
googleFonts: true
includeSubsets:
- force: true
  from: Noto Sans Devanagari
  layoutHandling: closure
  ranges:
  - end: 2431
    start: 2304
recipeProvider: noto
sources:
- NotoSans.glyphspackage
- NotoSans-Italic.glyphspackage
