name: Build, QA, Release

on: push

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build_font:
    uses: notofonts/notobuilder/.github/workflows/build.yaml@main
    secrets: inherit

